/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import { connect } from "react-redux";

import PopupItemList from "../components/popup-item-list";
import { selectItem, copiedField } from "../../actions";
import { parseFilterString, filterItem } from "../../filter";
const collator = new Intl.Collator();

export default connect(
  (state) => {
    const filter = parseFilterString(state.list.filter.query);
    const items = state.cache.items
                       .filter((i) => filterItem(filter, i))
                       .sort((a, b) => collator.compare(a.title, b.title));
    if (items.length || state.list.filter.userEntered) {
      return {items, noResultsBanner: false};
    }
    // An autogenerated filter that produced no results; show everything, plus
    // a banner informing users.
    return {items: state.cache.items, noResultsBanner: true};
  },
  (dispatch) => ({
    onClick: (id) => { dispatch(selectItem(id)); },
    onCopy: (field) => { dispatch(copiedField(field)); },
  }),
)(PopupItemList);
